### ISSUE TITLE
win10X64专业版，双击ClashZ无法运行，报错自动退出

### ISSUE THREAD

**Issue by Crazyguy2020** [Grergo/ClashZ#2]
Win10 X64专业版，.net framework 4.7.2已安装,

1、下载解压之后，双击程序无法运行（管理员权限也不行），报错如下：

错误应用程序名称: ClashZ.exe，版本: 1.0.0.1，时间戳: 0xfb819d8f
错误模块名称: KERNELBASE.dll，版本: 10.0.18362.778，时间戳: 0xafa78a6a
异常代码: 0xe0434352
错误偏移量: 0x000000000003a799
错误进程 ID: 0xeac
错误应用程序启动时间: 0x01d61b808c27bfd1
错误应用程序路径: D:\Program File\ClashZ\ClashZ.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: ddb4e722-dc00-4e33-8879-ebd402d2f857
错误程序包全名: 
错误程序包相对应用程序 ID: 

2、将【libs】文件夹里面移到根目录后，主程序能找开，提示无配置文件。我选择相应的.yml文件（已在Clash for windows成功运行），ClashZ报错退出，日记同上。
![微信截图_20200426122354](https://user-images.githubusercontent.com/49531214/80297974-fe663780-87ba-11ea-9a01-b2bf493aca23.png)
![1](https://user-images.githubusercontent.com/49531214/80298011-39686b00-87bb-11ea-96c3-2ae4972b7f65.png)
![2](https://user-images.githubusercontent.com/49531214/80298032-3d948880-87bb-11ea-9f9f-9d25a9cfe10d.png)

**Comment by Grergo** [comment]
看日志好像是yaml文件解析错误。可以贴一下配置文件吗，请把有关信息去掉。谢谢！

**Comment by Crazyguy2020** [comment]
> 看日志好像是yaml文件解析错误。可以贴一下配置文件吗，请把有关信息去掉。谢谢！

只去掉了服务器信息，后缀名 yml-》txt
[JiyouwangyiNoad.txt](https://github.com/Grergo/ClashZ/files/4535108/JiyouwangyiNoad.txt)

**Comment by Grergo** [comment]
1. 新版本已经修复，请使用新版本。
2. 或者将配置文件中的secret字段以及redir-port字段删除并将external-controller 修改为127.0.0.1:端口号 以保证安全
**注意：为避免其他问题，请先将自己的配置文件后缀名修改为yaml 并放入Profile目录下。**
_我之前并没有系统学过C# ，这个只是边学边做，Bug有些多请多多担待。_

**Comment by Crazyguy2020** [comment]
> 2\. redir-port

感谢作者更新
下载了最新版，删掉了Secret（redir-port找不到），改成了127.0.0.1。并把配置改成了config.yaml。双击能打开主程序ClashZ，但提示无法连接Clash-core（管理员权限也不行）。【节点】信息导入OK，【规则】信息导入OK，【策略】无信息NG。手动运行Clash.exe后，【策略】还是无法显示，无法科学上网

**Comment by Grergo** [comment]
看您的描述，好像是clash运行失败。请按以下步骤进行排查：

1.  运行clashz后，浏览器打开 http://127.0.0.1:端口号/configs 看看能否有信息显示
2.  如果没有信息显示，则表示clash没有运行，这一般是由于配置文件不正确引起的。
3. 打开clashz目录，进入到Core目录下，按住shift 右击空白区域，打开cmd/powershell ，键入clash.exe   -d ../Profile/ 运行，看是否有报错信息。如果有报错信息，请按照报错信息修改配置文件。如果不知道怎么修改，可以隐去服务器信息，发送到weikangwang730@gmail.com ，亦或者直接使用修改之前的配置文佳。

_感谢您的耐心_

**Comment by Grergo** [comment]
如果您没有问题，我将关闭此issue
