### ISSUE TITLE
win10 2004 专业版，无法连接clashcore

### ISSUE THREAD

**Issue by xqXQzzz1** [Grergo/ClashZ#3]

**Comment by Grergo** [comment]
请检查一下能否在core目录下执行 ./clash.exe  -d ../Profile/

**Comment by xqXQzzz1** [comment]
已经解决，是config.yaml为空的原因。
另外，建议策略组可以折叠。
我换用clashr的内核再导入配置（80+节点）点击策略或者节点就会卡死强退。

**Comment by Grergo** [comment]
好的，原谅我只有个位数的节点，没有考虑到这个问题
