### ISSUE TITLE
Clash订阅/托管链接导入

### ISSUE THREAD

**Issue by Riajyuu** [Grergo/ClashZ#4]
我看完 README 之后也不知道该怎么做这件事，然后翻 Clash 那边的 Wiki 我也没翻到

**Comment by Grergo** [comment]
暂时还没有托管链接导入功能，考虑在下个版本添加。我目前只是业余开发，精力有限。对您使用造成的不便，还请谅解。

**Comment by Grergo** [comment]
订阅/托管 没有接触过，如果确实需要此功能，请选择Clash for Windows。
